#!/usr/bin/env python

from app.models import Base, engine, Config, Session


def reset_db():
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)


def create_default_config():
    session = Session()
    session.add(Config(app_name="PyTweet"))
    session.commit()


if __name__ == "__main__":
    reset_db()
    create_default_config()
