#!/usr/bin/env python

from app.models import Base, engine, Config, session

if __name__ == "__main__":
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)

    config = Config(app_name="PyTweet")
    session = session()
    session.add(config)
    session.commit()