#!/usr/bin/env python

from app import routes

if __name__ == '__main__':
    routes.app.debug = True
    routes.app.logger.info("Starting")
    routes.app.run(host='0.0.0.0', port=8000, threaded=True)
