# -*- mode: ruby -*-
# vi: set ft=ruby

provision_script = <<SCRIPT
set -o errexit
set -o pipefail
set -o nounset
shopt -s failglob
set -o xtrace
export DEBIAN_FRONTEND=noninteractive
curl -sL https://deb.nodesource.com/setup_iojs_1.x | sudo bash -
apt-get install -y iojs
exec sudo -i -u vagrant /bin/bash -- << EOF
cd /vagrant
npm install --save react react-dom
EOF
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
  end

  config.vm.provision "shell", inline: provision_script
  config.vm.network "forwarded_port", guest: 3000, host: 3000
end
